import type { MoleculeUITheme } from './theme.types';
import {
  ColorPrimary,
  ColorPrimaryHover,
  ColorPrimaryActive,
  ColorPrimaryLight,
  ColorBrand,
  ColorBrandHover,
  ColorBrandActive,
  ColorBrandLight,
  ColorSuccess,
  ColorSuccessHover,
  ColorSuccessActive,
  ColorSuccessLight,
  ColorDanger,
  ColorDangerHover,
  ColorDangerActive,
  ColorDangerLight,
  ColorWarning,
  ColorWarningHover,
  ColorWarningActive,
  ColorWarningLight,
  ColorPrimaryText,
  ColorBrandText,
  ColorSuccessText,
  ColorDangerText,
  ColorWarningText,
  ColorBackground,
  ColorSurface,
  ColorSurfaceHover,
  ColorTextPrimary,
  ColorTextSuccess,
  ColorTextOnPrimary,
  ColorTextOnSecondary,
  ColorTextOnDanger,
  ColorTextOnWarning,
  ColorTextDisabled,
  ColorBorder,
  ColorBorderFocus,
  ColorDisabled,
  ColorFocusRing,
  SpacingXs,
  SpacingSm,
  SpacingMd,
  SpacingLg,
  SpacingXl,
  SpacingXxl,
  FontFamilyBase,
  FontSizeXs,
  FontSizeSm,
  FontSizeMd,
  FontSizeLg,
  FontWeightNormal,
  FontWeightMedium,
  FontWeightSemibold,
  FontWeightBold,
  LineHeightTight,
  LineHeightNormal,
  LineHeightRelaxed,
  BorderRadiusSm,
  BorderRadiusMd,
  BorderRadiusLg,
  BorderRadiusFull,
  TransitionFast,
  TransitionNormal,
} from './tokens.generated';

export const defaultTheme: MoleculeUITheme = {
  colors: {
    primary: ColorPrimary,
    primaryHover: ColorPrimaryHover,
    primaryActive: ColorPrimaryActive,
    primaryLight: ColorPrimaryLight,

    brand: ColorBrand,
    brandHover: ColorBrandHover,
    brandActive: ColorBrandActive,
    brandLight: ColorBrandLight,

    success: ColorSuccess,
    successHover: ColorSuccessHover,
    successActive: ColorSuccessActive,
    successLight: ColorSuccessLight,

    danger: ColorDanger,
    dangerHover: ColorDangerHover,
    dangerActive: ColorDangerActive,
    dangerLight: ColorDangerLight,

    warning: ColorWarning,
    warningHover: ColorWarningHover,
    warningActive: ColorWarningActive,
    warningLight: ColorWarningLight,

    primaryText: ColorPrimaryText,
    brandText: ColorBrandText,
    successText: ColorSuccessText,
    dangerText: ColorDangerText,
    warningText: ColorWarningText,

    background: ColorBackground,
    surface: ColorSurface,
    surfaceHover: ColorSurfaceHover,

    textPrimary: ColorTextPrimary,
    textSuccess: ColorTextSuccess,
    textOnPrimary: ColorTextOnPrimary,
    textOnSecondary: ColorTextOnSecondary,
    textOnDanger: ColorTextOnDanger,
    textOnWarning: ColorTextOnWarning,
    textDisabled: ColorTextDisabled,

    border: ColorBorder,
    borderFocus: ColorBorderFocus,

    disabled: ColorDisabled,
    focusRing: ColorFocusRing,
  },
  spacing: {
    xs: SpacingXs,
    sm: SpacingSm,
    md: SpacingMd,
    lg: SpacingLg,
    xl: SpacingXl,
    xxl: SpacingXxl,
  },
  typography: {
    fontFamily: FontFamilyBase,
    fontSize: {
      xs: FontSizeXs,
      sm: FontSizeSm,
      md: FontSizeMd,
      lg: FontSizeLg,
    },
    fontWeight: {
      normal: FontWeightNormal,
      medium: FontWeightMedium,
      semibold: FontWeightSemibold,
      bold: FontWeightBold,
    },
    lineHeight: {
      tight: LineHeightTight,
      normal: LineHeightNormal,
      relaxed: LineHeightRelaxed,
    },
  },
  radii: {
    sm: BorderRadiusSm,
    md: BorderRadiusMd,
    lg: BorderRadiusLg,
    full: BorderRadiusFull,
  },
  transitions: {
    fast: TransitionFast,
    normal: TransitionNormal,
  },
};
